syntax = "proto3";

package user.v1;

option go_package = "github.com/BwCloudWeGo/bw-cli/api/gen/user/v1;userv1";

service UserService {
  rpc Register(RegisterRequest) returns (UserResponse);
  rpc Login(LoginRequest) returns (UserResponse);
  rpc GetUser(GetUserRequest) returns (UserResponse);
}

message RegisterRequest {
  string account = 1;
  string display_name = 2;
  string password = 3;
}

message LoginRequest {
  string account = 1;
  string password = 2;
}

message GetUserRequest {
  string id = 1;
}

message UserResponse {
  string id = 1;
  string account = 2;
  string display_name = 3;
}
